version: "3.3"
services:
    web:
        image: hello_world_django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"